framework:
    messenger:
        buses:
            command_bus:
                middleware:
                - 'App\Middleware\AuditMiddleware'

            event_bus:
                default_middleware: 'allow_no_handlers'
                middleware:
                - 'App\Middleware\AuditMiddleware'

        transports:
            # Uncomment the following line to enable a transport named "amqp"
            http: '%env(MESSENGER_HTTP_DSN)%'
            amqp: '%env(MESSENGER_TRANSPORT_DSN)%'
            amqp2: '%env(MESSENGER_TRANSPORT_DSN)%'

        routing:
            # Route your messages to the transports
#             'App\Message\ReportGame': amqp
             'App\Message\LoserBet' : http
             'App\Message\WinnerBet' : amqp
